# Generated by Django 3.2.12 on 2022-03-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('banner_image', models.CharField(max_length=2000, null=True)),
                ('description', models.CharField(max_length=20000, null=True)),
                ('one_day_volume', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('seven_day_volume', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('thirty_day_volume', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('num_owners', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=2000, null=True)),
                ('external_link', models.CharField(max_length=2000, null=True)),
                ('safelist_request_status', models.CharField(max_length=2000, null=True)),
                ('credibility_rating', models.DecimalField(decimal_places=1, default=0, max_digits=8, null=True)),
                ('votes', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
