# Generated by Django 3.1.7 on 2022-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('banner_image', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=20000)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_owners', models.DecimalField(decimal_places=2, max_digits=8)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=2000)),
                ('external_link', models.CharField(max_length=2000)),
                ('safelist_request_status', models.CharField(max_length=2000)),
            ],
        ),
    ]
