# Generated by Django 3.1.7 on 2022-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftproject',
            name='banner_image',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='description',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='external_link',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='floor_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='image',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='num_owners',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='safelist_request_status',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
