# Generated by Django 3.1.7 on 2022-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0002_auto_20220326_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftproject',
            name='credibility_rating',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='nftproject',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
