# Generated by Django 3.1.7 on 2022-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='num_owners',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
