# Generated by Django 3.1.7 on 2022-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0003_auto_20220326_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftproject',
            name='credibility_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
