# Generated by Django 3.1.7 on 2022-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0003_auto_20220327_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftproject',
            name='total_cred',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, null=True),
        ),
    ]
