# Generated by Django 3.1.7 on 2022-03-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0004_auto_20220326_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftproject',
            name='one_day_volume',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='nftproject',
            name='seven_day_volume',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='nftproject',
            name='thirty_day_volume',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='nftproject',
            name='credibility_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, null=True),
        ),
    ]
