# Generated by Django 3.2.12 on 2022-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0004_auto_20220326_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftproject',
            name='credibility_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, null=True),
        ),
    ]
