# Generated by Django 3.1.7 on 2022-03-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugapp', '0005_auto_20220326_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20000, null=True)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugapp.nftproject')),
            ],
        ),
    ]
